logging:
  level:
    root: "DEBUG"
app:
  generator:
    prop: "some prop"
    strings:
      - "a"
      - "b"
    instruments:
      - symbol: "GOOGL"
        initialPrice: 1400.00
        maxPercentageDiff: 2
        minTickDelay: 2000
        maxTickDelay: 5000
      - symbol: "USD/PLN"
        initialPrice: 3.89
        maxPercentageDiff: 5
        minTickDelay: 500
        maxTickDelay: 3000