logging:
  level:
    root: "INFO"
server:
  port: 8080
app:
  url-tick-service: "http://localhost:${server.port}"
  generator:
    instruments:
      - symbol: "GOOGL"
        initialPrice: 1400.00
        maxPercentageDiff: 2
        minTickDelay: 2000
        maxTickDelay: 5000
      - symbol: "USD/PLN"
        initialPrice: 3.89
        maxPercentageDiff: 3
        minTickDelay: 500
        maxTickDelay: 3000